puts "The students of my cohort at Makers Academy"
puts "--------------------"
puts "Jean Baptiste"
puts "James Brook"
puts "Nicki"
puts "James"
puts "Gianni"
puts "Jeremy"
puts "Michael"
puts "Nisar"
puts "Asta"
puts "Peter"
print "Overall, we have "
print 10
puts " Great students"